---
- name: "Install Jenkins, Java and Python on EC2 Instance"
  hosts: projectserver
  become: yes
  vars:
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  tasks: 
    - name: Add Jenkins apt repository key
      shell: wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key

    - name: Add Jenkins apt repository on Server
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] http://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Update apt package index after adding Jenkins repository
      apt:
        update_cache: yes

    - name: Install Jenkins on Server
      apt:
        name: jenkins
        state: present

    - name: Install Java on Server
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install Python on Server
      apt:
        name: python3
        state: present

    - name: Started and enable jenkins Service
      systemd:
        name: jenkins
        enabled: yes
        state: started
    
    - name: Get the InitialAdminPassword
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: output
    
    - debug: msg="{{ output.stdout_lines }}"
